spin_version = "1"
authors = ["francesco"]
description = ""
name = "FastMensa"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "fast-mensa"
source = "target/wasm32-wasi/release/fast_mensa.wasm"
allowed_http_hosts = []
files =   ["db/utenti.txt"]
[component.trigger]
route = "/App"
[component.build]
command = "cargo build --target wasm32-wasi --release"
